package cli

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/stephrobert/feint/internal/drift"
)

// The coverage tables in the README are generated, and this is why.
//
// They were written by hand, and they said Scaleway served 12 routes, Outscale
// 3 and Exoscale 5. The real counts on the day this was written were 55, 20 and
// 5. Nobody had lied; the numbers had simply been true once. A README that
// advertises a quarter of what the emulator does is worse than one that says
// nothing, because a reader who checks a number and finds it wrong stops
// checking the others.
//
// So the numbers come from the same artefacts the CI gate reads —
// coverage/<provider>-coverage.json, regenerated by `mise run drift:update` —
// and from the route table the packs mount in process. Neither can be edited
// into agreement with a claim.
//
// --check is what keeps it honest: it re-renders and compares, exiting 2 like
// every other drift gate here. The pre-commit hook and CI run it, so a route
// added without regenerating fails before it is merged.

const (
	docsStartMarker = "<!-- coverage:start -->"
	docsEndMarker   = "<!-- coverage:end -->"
	// The banner is the sample output of `feint serve` at the top of the
	// README. It carried a hand-written route count that said 12 / 3 / 5 when
	// the real one was 55 / 20 / 14 — the same failure as the tables, in the
	// paragraph above them, left behind when the tables were fixed.
	bannerStartMarker = "<!-- banner:start -->"
	bannerEndMarker   = "<!-- banner:end -->"
	// The contract policy table, in docs/limits.md. It used to be three
	// hand-written paragraphs, and the numbers in them went wrong twice: once by
	// going stale, once by being recomputed from the extractor's own
	// --assume-closed flag, which measures this project's assumption rather than
	// anything the provider declares.
	contractsStartMarker = "<!-- contracts:start -->"
	contractsEndMarker   = "<!-- contracts:end -->"
	// docsGenerated warns whoever opens the README with an editor. The marker
	// pair alone is easy to miss between two paragraphs of prose.
	docsGenerated = "<!-- Generated by `mise run docs:coverage`. Do not edit by hand. -->"
)

// The artefact's shape is drift.CoverageFile, imported rather than redeclared.
//
// A hand-written copy used to live here, defended by a comment saying a separate
// declaration "must keep working — or fail loudly — if the writer changes
// shape". It cannot fail loudly, and that is the whole lesson: encoding/json
// drops an unknown field and zeroes a missing one, which is how the conformance
// view, declared twice in this same package, made `feint status` report 0 for
// the number it exists to report. One shape, one owner.

// docs regenerates the generated sections of a Markdown file.
func docs(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("docs", flag.ContinueOnError)
	target := fs.String("file", "README.md", "the Markdown file holding the generated section")
	dir := fs.String("coverage", "coverage", "directory holding the versioned coverage artefacts")
	contractsDir := fs.String("contracts", "contracts", "directory holding the API description artefacts")
	limits := fs.String("limits", "docs/limits.md", "the Markdown file holding the contract policy table (empty to skip)")
	routesDoc := fs.String("routes", "docs/routes.md", "the Markdown file holding the route reference (empty to skip)")
	confidenceDoc := fs.String("confidence", "docs/confidence.md", "the Markdown file holding the confidence page (empty to skip)")
	installDoc := fs.String("install", "docs/install.md", "the Markdown file holding the prerequisites (empty to skip)")
	workflow := fs.String("workflow", conformanceWorkflow, "the workflow the client versions are read from")
	ansible := fs.String("client-pins", ansibleClientPins, "the Ansible defaults the workflow pins are compared against (empty to skip)")
	check := fs.Bool("check", false, "do not write; exit 2 when the file is out of date")
	screenshots := fs.String("screenshots", "docs/assets/ui/manifest.json", "the manifest of the page's screenshots (empty to skip)")
	// Written by tools/ui/screenshots.sh once the browser has taken them. It is
	// this binary's job because the digest recorded there is of the page this
	// binary serves, and a second implementation of that in the harness would be
	// one fact in two places.
	writeManifest := fs.String("ui-manifest", "", "record the page's digest beside the screenshots at this path, and do nothing else")
	if err := fs.Parse(args); err != nil {
		return exitError
	}

	if *writeManifest != "" {
		if err := writeScreenshotManifest(*writeManifest, stdout); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
		return exitOK
	}

	order, routes, err := routesByProvider()
	if err != nil {
		fmt.Fprintf(stderr, "feint: %v\n", err)
		return exitError
	}

	reports, err := loadCoverage(*dir)
	if err != nil {
		fmt.Fprintf(stderr, "feint: %v\n", err)
		return exitError
	}
	if len(reports) == 0 {
		fmt.Fprintf(stderr, "feint: no coverage artefact in %s; run `mise run drift:update` first\n", *dir)
		return exitError
	}

	current, err := os.ReadFile(*target)
	if err != nil {
		fmt.Fprintf(stderr, "feint: %v\n", err)
		return exitError
	}

	updated, err := spliceSection(string(current), docsStartMarker, docsEndMarker,
		renderCoverage(reports, routes))
	if err != nil {
		fmt.Fprintf(stderr, "feint: %v\n", err)
		return exitError
	}
	// The banner is optional: a Markdown file that only wants the tables is a
	// legitimate target, and failing it over a marker it never claimed to have
	// would make --coverage on another document useless.
	if strings.Contains(updated, bannerStartMarker) {
		updated, err = spliceSection(updated, bannerStartMarker, bannerEndMarker, renderBanner(order, routes))
		if err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
	}
	// The client matrix, on the same optional terms. Its source is the workflow
	// that installs the clients, so the versions on the page and the versions the
	// suite runs cannot drift apart.
	if strings.Contains(updated, clientsStartMarker) {
		rendered, cErr := renderClients(*workflow, conformanceRoot)
		if cErr != nil {
			// The likeliest cause is a document that claims the marker outside
			// this repository, where the workflow it reads does not exist. Say
			// which file was missing rather than only that something was.
			fmt.Fprintf(stderr, "feint: the client matrix needs %s: %v\n", *workflow, cErr)
			return exitError
		}
		updated, err = spliceSection(updated, clientsStartMarker, clientsEndMarker, rendered)
		if err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
	}

	// The prerequisites, on the same optional terms. Their source is `go.mod`
	// and the version constants the doctor checks against, so the page cannot
	// recommend a version nothing measures.
	if strings.Contains(updated, prereqStartMarker) {
		updated, err = spliceSection(updated, prereqStartMarker, prereqEndMarker, renderPrereq(goModPath))
		if err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
	}
	// The install commands, whose asset names come from the release build
	// matrix and whose verification travels with them.
	if strings.Contains(updated, installStartMarker) {
		rendered, iErr := renderInstall(releaseWorkflow, goModPath, changelogPath)
		if iErr != nil {
			fmt.Fprintf(stderr, "feint: %v\n", iErr)
			return exitError
		}
		updated, err = spliceSection(updated, installStartMarker, installEndMarker, rendered)
		if err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
	}

	// A second file, written and checked on the same terms. Skipped without
	// complaint when it is absent: a user who installed the binary has no docs/
	// directory, and `feint docs` must still regenerate their README.
	limitsChanged, limitsErr := spliceContracts(*limits, *contractsDir)
	if limitsErr != nil {
		fmt.Fprintf(stderr, "feint: %v\n", limitsErr)
		return exitError
	}

	// A third, on the same terms again: the route reference, written by the
	// process that mounts the routes it lists — each route with the proofs the
	// recorded conformance run earned it (#123), read from the versioned
	// artefact so the page can never carry a level whose evidence is gone.
	evidenceArt, evErr := loadEvidenceArtefact(filepath.Join(*dir, "evidence.json"))
	if evErr != nil {
		fmt.Fprintf(stderr, "feint: %v\n", evErr)
		return exitError
	}
	// The same artefacts the tables read decide which section a route files
	// under, so the reference page and the README can never disagree on where
	// an operation belongs.
	opGroups := operationGroups(reports)
	routesChanged, routesErr := spliceRoutes(*routesDoc, evidenceArt, opGroups)
	if routesErr != nil {
		fmt.Fprintf(stderr, "feint: %v\n", routesErr)
		return exitError
	}

	// The confidence page's two figures (#130): the same artefact the routes
	// page reads, so a reader cannot be told two different numbers by two pages.
	confidenceChanged, confidenceErr := spliceConfidence(*confidenceDoc, evidenceArt)
	if confidenceErr != nil {
		fmt.Fprintf(stderr, "feint: %v\n", confidenceErr)
		return exitError
	}

	// A fourth: the install page, which carries the same prerequisites and the
	// same install commands as the README. It is the page a release dates
	// fastest, and the only one whose numbers nobody re-measures when cutting
	// one.
	// A fifth: the status table, whose "proven by" column is read from the
	// conformance workflow rather than maintained. It said Outscale was proven
	// by Terraform, which was true of the fixture and false of CI — a claim a
	// reader had to compare two files to falsify (#147's family).
	safetyChanged, safetyErr := spliceSafety(filepath.Dir(*target))
	if safetyErr != nil {
		fmt.Fprintf(stderr, "feint: %v\n", safetyErr)
		return exitError
	}
	statusChanged, statusErr := spliceStatus(*target, conformanceWorkflow)
	if statusErr != nil {
		fmt.Fprintf(stderr, "feint: %v\n", statusErr)
		return exitError
	}

	installChanged, installErr := splicePrereq(*installDoc, goModPath)
	if installErr != nil {
		fmt.Fprintf(stderr, "feint: %v\n", installErr)
		return exitError
	}
	commandsChanged, commandsErr := spliceInstall(*installDoc, releaseWorkflow, goModPath, changelogPath)
	if commandsErr != nil {
		fmt.Fprintf(stderr, "feint: %v\n", commandsErr)
		return exitError
	}
	// The container section, on the same terms: its image name is checked
	// against the release workflow and its version against the CHANGELOG.
	containerChanged, containerErr := spliceContainer(*installDoc, releaseWorkflow, goModPath, changelogPath)
	if containerErr != nil {
		fmt.Fprintf(stderr, "feint: %v\n", containerErr)
		return exitError
	}

	// Not generated sections but comparisons, and they belong to the same gate.
	// Reported in both modes, because an operator running `feint docs` to fix
	// the pages must not be told everything is fine: neither of these is
	// repaired by regenerating, both need a decision.
	problems := clientPinMismatches(*workflow, *ansible)
	problems = append(problems, documentedAssetMismatches(releaseWorkflow, *target, *installDoc)...)
	if len(problems) > 0 {
		for _, line := range problems {
			fmt.Fprintf(stderr, "feint: %s\n", line)
		}
		fmt.Fprintln(stderr, "feint: fix the disagreement itself; regenerating will not")
		return exitDrift
	}

	if *check {
		// Two staleness questions, and they are different. Does the document
		// match the artefacts, and do the artefacts match the code? The first
		// was gated from the start; the second was not, so a route added
		// without regenerating left the coverage figures behind and only the
		// weekly CI job would eventually notice. Exoscale mounted fourteen
		// routes while its artefact reported five.
		if stale := staleCoverage(reports, routes); len(stale) > 0 {
			for _, line := range stale {
				fmt.Fprintf(stderr, "feint: %s\n", line)
			}
			fmt.Fprintln(stderr, "feint: the coverage artefacts are behind the code; run `mise run drift:update`")
			return exitDrift
		}
		if updated != string(current) {
			fmt.Fprintf(stderr, "feint: %s is out of date; run `mise run docs:coverage`\n", *target)
			return exitDrift
		}
		if statusChanged {
			fmt.Fprintf(stderr, "feint: the status table in %s is behind the conformance workflow; run `feint docs`\n", *target)
			return exitDrift
		}
		if safetyChanged {
			fmt.Fprintf(stderr, "feint: the safety banner is behind the artefacts it counts; run `feint docs`\n")
			return exitDrift
		}
		if limitsChanged {
			fmt.Fprintf(stderr, "feint: %s is out of date; run `mise run docs:coverage`\n", *limits)
			return exitDrift
		}
		if routesChanged {
			fmt.Fprintf(stderr, "feint: %s is out of date; run `mise run docs:coverage`\n", *routesDoc)
			return exitDrift
		}
		if confidenceChanged {
			fmt.Fprintf(stderr, "feint: %s is out of date; run `mise run docs:coverage`\n", *confidenceDoc)
			return exitDrift
		}
		if installChanged || commandsChanged || containerChanged {
			fmt.Fprintf(stderr, "feint: %s is out of date; run `mise run docs:coverage`\n", *installDoc)
			return exitDrift
		}
		// The screenshots of the page, on the same gate as every other generated
		// document. A picture of a screen goes stale exactly like a table of
		// numbers, and the only difference is that nobody notices for longer.
		if *screenshots != "" {
			if state, why := checkScreenshots(*screenshots); state == screenshotsStale {
				fmt.Fprintf(stderr, "feint: %s; run `mise run docs:ui`\n", why)
				return exitDrift
			}
		}
		fmt.Fprintf(stdout, "%s is up to date\n", *target)
		return exitOK
	}
	if safetyChanged {
		if err := writeSplicedSafety(filepath.Dir(*target)); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
		fmt.Fprintf(stdout, "the safety banner now matches the artefacts it counts\n")
	}
	if statusChanged {
		if err := writeSplicedStatus(*target, conformanceWorkflow); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
		fmt.Fprintf(stdout, "%s status table updated\n", *target)
	}
	if limitsChanged {
		if err := writeSplicedContracts(*limits, *contractsDir); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
		fmt.Fprintf(stdout, "%s updated\n", *limits)
	}
	if routesChanged {
		if err := writeSplicedRoutes(*routesDoc, evidenceArt, opGroups); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
		fmt.Fprintf(stdout, "%s updated\n", *routesDoc)
	}
	if confidenceChanged {
		if err := writeSplicedConfidence(*confidenceDoc, evidenceArt); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
		fmt.Fprintf(stdout, "%s updated\n", *confidenceDoc)
	}
	if installChanged {
		if err := writeSplicedPrereq(*installDoc, goModPath); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
	}
	// After the prerequisites, never before: both rewrite the same file, and
	// this one re-reads it to keep the section the other just wrote.
	if commandsChanged {
		if err := writeSplicedInstall(*installDoc, releaseWorkflow, goModPath, changelogPath); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
	}
	// Third writer of the same file, so it re-reads after the two above.
	if containerChanged {
		if err := writeSplicedContainer(*installDoc, releaseWorkflow, goModPath, changelogPath); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
	}
	if installChanged || commandsChanged || containerChanged {
		fmt.Fprintf(stdout, "%s updated\n", *installDoc)
	}

	if updated == string(current) {
		fmt.Fprintf(stdout, "%s already up to date\n", *target)
		return exitOK
	}
	if err := os.WriteFile(*target, []byte(updated), 0o644); err != nil { //nolint:gosec // a README is world-readable by design
		fmt.Fprintf(stderr, "feint: %v\n", err)
		return exitError
	}
	fmt.Fprintf(stdout, "%s updated\n", *target)
	return exitOK
}

// staleCoverage reports providers whose committed artefact no longer matches
// what the packs mount.
//
// The comparison is per measured product, and it counts *routes*, not
// operations, only where the two coincide — which they do here: this project
// mounts one route per upstream operation, and the route-table check already
// fails a route whose Operation matches nothing upstream. Products the coverage
// gate does not scan are skipped rather than counted as a mismatch: routes are
// legitimately mounted for iam and marketplace, and the README says so
// separately.
//
// This cannot replace the drift gate. It answers "did somebody forget to
// regenerate", not "did upstream move" — which is why it points at
// drift:update rather than claiming drift.
func staleCoverage(reports []drift.CoverageFile, routes map[string]map[string]int) []string {
	var out []string
	for _, rep := range reports {
		byProduct := routes[rep.Provider]
		for _, product := range rep.Products {
			mounted := byProduct[product.Product]
			if mounted != product.Implemented {
				out = append(out, fmt.Sprintf(
					"%s/%s: %d route(s) mounted, the artefact reports %d implemented",
					rep.Provider, product.Product, mounted, product.Implemented))
			}
		}
	}
	sort.Strings(out)
	return out
}

// routesByProvider counts what the packs actually mount, in process, grouped by
// the upstream product each route serves. This is the same source the server
// serves from, so the count cannot drift from what a client would find at
// /_feint/routes.
//
// The grouping is what makes the unmeasured products visible. The Scaleway gate
// runs on instance, vpc and ipam, so routes serving iam or marketplace are
// mounted against a surface nobody scans — six of them, on the day this was
// written. A table reporting 55 routes next to 49 served operations and saying
// nothing about the gap invites the reader to assume a rounding error.
// The order returned beside the counts is the mount order, because the banner
// must print providers in the order the server does and a map has none.
func routesByProvider() ([]string, map[string]map[string]int, error) {
	srv, _, err := newServer(nil)
	if err != nil {
		return nil, nil, err
	}
	var order []string
	counts := make(map[string]map[string]int)
	for _, p := range srv.Packs() {
		byProduct := make(map[string]int)
		for _, r := range p.Routes() {
			byProduct[productOf(r.Operation)]++
		}
		order = append(order, p.Name())
		counts[p.Name()] = byProduct
	}
	return order, counts, nil
}

// productOf takes the product an operation belongs to, which every provider
// spells as the first segment: instance/v1/API.ListServers, osc/Client.ReadVms,
// exoscale/v2.list-instances.
func productOf(operation string) string {
	if i := strings.Index(operation, "/"); i > 0 {
		return operation[:i]
	}
	return operation
}

// routeTotal sums a provider's mounted routes.
func routeTotal(byProduct map[string]int) int {
	total := 0
	for _, n := range byProduct {
		total += n
	}
	return total
}

// unmeasured names the products a provider mounts routes for and the coverage
// artefact does not cover, with their route counts.
func unmeasured(rep drift.CoverageFile, byProduct map[string]int) []string {
	measured := make(map[string]bool, len(rep.Products))
	for _, p := range rep.Products {
		measured[p.Product] = true
	}
	var out []string
	for product, n := range byProduct {
		if !measured[product] {
			out = append(out, fmt.Sprintf("`%s` (%d)", product, n))
		}
	}
	sort.Strings(out)
	return out
}

// operationGroups maps every operation the coverage artefacts know to the group
// it counts under — the upstream's own grouping, its product where the upstream
// declares none. One map across providers, because operation names already
// carry their provider's namespace and the route reference looks them up flat.
func operationGroups(reports []drift.CoverageFile) map[string]string {
	out := make(map[string]string)
	for _, rep := range reports {
		for _, e := range rep.Entries {
			out[e.Operation] = e.GroupName()
		}
	}
	return out
}

// loadCoverage reads every <provider>-coverage.json in dir, ordered by provider
// so two runs render the same document.
func loadCoverage(dir string) ([]drift.CoverageFile, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*-coverage.json"))
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)

	reports := make([]drift.CoverageFile, 0, len(paths))
	for _, path := range paths {
		f, err := os.Open(path) //nolint:gosec // the path comes from our own glob
		if err != nil {
			return nil, err
		}
		rep, decodeErr := drift.LoadCoverage(f)
		_ = f.Close()
		if decodeErr != nil {
			return nil, fmt.Errorf("%s: %w", path, decodeErr)
		}
		reports = append(reports, rep)
	}
	return reports, nil
}

// renderCoverage builds the Markdown. One table per provider, its rows the
// upstream's own grouping of its surface, because a group is the unit a
// decision is taken on: a single row saying "Scaleway 49/179" hides that
// Instance is nearly done and VPC is barely started.
//
// The grouping is the upstream's, never one invented here: Scaleway's SDK
// packages, Outscale's document tags, the roots of Exoscale's tag hierarchy.
// Before the artefacts carried it, Scaleway showed six rows because its SDK has
// a package per product while Outscale's 236 operations sat in one `osc` row
// and Exoscale's 374 in one `exoscale` row — a difference that read as depth
// when it was only SDK layout, and that hid the one distinction these tables
// exist to make: Exoscale's "12% served" is 39% managed databases declined by
// the roadmap, not 88% missing.
func renderCoverage(reports []drift.CoverageFile, routes map[string]map[string]int) string {
	// Most served first, name breaking the tie. Alphabetical would open on the
	// least finished pack, and the order still has to be a function of the data
	// so two runs render the same bytes.
	sort.SliceStable(reports, func(i, j int) bool {
		li, lj := routeTotal(routes[reports[i].Provider]), routeTotal(routes[reports[j].Provider])
		if li != lj {
			return li > lj
		}
		return reports[i].Provider < reports[j].Provider
	})

	var b strings.Builder
	b.WriteString(docsGenerated)
	b.WriteString("\n\n")

	total := 0
	for _, rep := range reports {
		total += routeTotal(routes[rep.Provider])
	}
	fmt.Fprintf(&b,
		"%d routes are mounted across the three packs. The tables count *upstream operations*\n"+
			"rather than routes: what the provider's own SDK or API description declares, against\n"+
			"what this emulator serves, declines on purpose, or has not triaged yet.\n\n",
		total)

	for _, rep := range reports {
		byProduct := routes[rep.Provider]
		fmt.Fprintf(&b, "#### %s\n\n", strings.ToUpper(rep.Provider[:1])+rep.Provider[1:])
		// Three shares, not one: "12% served" alone reads as 88% missing, when
		// most of the gap is operations somebody decided to refuse. The
		// distinction between a refusal and an absence is the one these tables
		// exist to make, so the headline makes it before the rows do.
		fmt.Fprintf(&b, "%d routes mounted. Of the %d operations upstream declares: %s served,\n%s declined on purpose, %s untriaged.\n\n",
			routeTotal(byProduct), rep.Total,
			percent(rep.Implemented, rep.Total), percent(rep.Declined, rep.Total), percent(rep.Unknown, rep.Total))
		named, rest, foldedGroups := foldSmallGroups(groupRows(rep), rep.Total)
		b.WriteString("| Group | Served | Declined | Untriaged | Upstream |\n")
		b.WriteString("|---|--:|--:|--:|--:|\n")
		for _, g := range named {
			fmt.Fprintf(&b, "| `%s` | %d | %d | %d | %d |\n",
				g.Group, g.Implemented, g.Declined, g.Unknown, g.Total)
		}
		if foldedGroups > 0 {
			fmt.Fprintf(&b, "| *… %d smaller groups* | %d | %d | %d | %d |\n",
				foldedGroups, rest.Implemented, rest.Declined, rest.Unknown, rest.Total)
		}
		fmt.Fprintf(&b, "| **Total** | **%d** | **%d** | **%d** | **%d** |\n\n",
			rep.Implemented, rep.Declined, rep.Unknown, rep.Total)

		// Said out loud rather than left as an unexplained arithmetic gap
		// between the routes and the served column.
		if outside := unmeasured(rep, byProduct); len(outside) > 0 {
			fmt.Fprintf(&b,
				"Routes are also mounted for %s, which the coverage gate does not scan yet:\n"+
					"they are served against a surface nobody measures, so no drift would be\n"+
					"reported if it moved.\n\n",
				strings.Join(outside, ", "))
		}
	}

	b.WriteString("Rows are the provider's own grouping of its surface — Scaleway's SDK products,\n")
	b.WriteString("Outscale's API tags, the roots of Exoscale's tag hierarchy — never a grouping\n")
	b.WriteString("invented here. Groups under 2% of a surface fold into the *smaller groups* row\n")
	b.WriteString("of their table, counts intact, so no block-sized decision can hide in it.\n\n")
	b.WriteString("**Declined** is a decision, not a gap: an operation nobody intends to emulate,\n")
	b.WriteString("with the reason in the pack's `Declined()`. **Untriaged** is the honest column —\n")
	b.WriteString("upstream operations nobody has ruled on yet. A new one appearing there fails CI\n")
	b.WriteString("until somebody decides, which is the whole point of measuring the surface\n")
	b.WriteString("instead of following it by hand.\n")

	return b.String()
}

// groupRows returns the rows of one provider's table: the upstream groups when
// the artefact carries them, its products otherwise — an artefact written
// before groups existed still renders, it just renders what it knows.
func groupRows(rep drift.CoverageFile) []drift.GroupCount {
	if len(rep.Groups) > 0 {
		return rep.Groups
	}
	rows := make([]drift.GroupCount, 0, len(rep.Products))
	for _, p := range rep.Products {
		rows = append(rows, drift.GroupCount{
			Group:       p.Product,
			Total:       p.Total,
			Implemented: p.Implemented,
			Declined:    p.Declined,
			Unknown:     p.Unknown,
		})
	}
	return rows
}

// foldSmallGroups splits a provider's groups into the rows worth naming and one
// explicit residual, so a 50-tag surface does not become a 50-row table.
//
// The floor is 2% of the provider's surface. It is a share rather than a count
// so the same sentence holds for a 236-operation provider and a 374-operation
// one, and it is what bounds the lie a fold can tell: nothing a reader would
// call a block — Exoscale's 146 dbaas refusals, Outscale's 24 Policy ones —
// can ever land in the residual, because a block is precisely a group too big
// for the floor. Asserted by TestFoldSmallGroupsNeverFoldsABlockDecision, which
// fails if a group at or above the floor stops being named.
//
// Named rows come back largest first, name breaking ties, because the table's
// job is comparative and the biggest block is the first thing to compare. The
// residual keeps exact counts: folding is about naming, never about numbers.
// One small group folds into nothing — a residual of one would hide a name to
// save no space.
func foldSmallGroups(groups []drift.GroupCount, total int) (named []drift.GroupCount, rest drift.GroupCount, foldedGroups int) {
	var small []drift.GroupCount
	for _, g := range groups {
		// Strictly under 2%: g is named when g.Total/total >= 1/50, kept in
		// integers so the comparison is exact.
		if g.Total*50 >= total {
			named = append(named, g)
		} else {
			small = append(small, g)
		}
	}
	if len(small) == 1 {
		named = append(named, small[0])
		small = nil
	}
	sort.SliceStable(named, func(i, j int) bool {
		if named[i].Total != named[j].Total {
			return named[i].Total > named[j].Total
		}
		return named[i].Group < named[j].Group
	})
	for _, g := range small {
		rest.Total += g.Total
		rest.Implemented += g.Implemented
		rest.Declined += g.Declined
		rest.Unknown += g.Unknown
	}
	return named, rest, len(small)
}

// renderBanner reproduces what `feint serve` prints on startup, so the example
// in the README is the program's own output rather than a memory of it.
//
// The provider order is the one the server mounts packs in, not an alphabetical
// one, because the point is to match what a reader will see in their terminal.
// It arrives from routesByProvider rather than being written here: a hardcoded
// list held this banner at three providers, so mounting a fourth pack turned
// `feint docs --check` red until somebody found this line — the treasure hunt
// docs/fourth-pack.md recorded.
func renderBanner(order []string, routes map[string]map[string]int) string {
	var b strings.Builder
	// The line the binary actually prints, format string and all. It carried
	// neither the version nor the real default address, which meant a reader
	// comparing the README with their terminal found two differences in the
	// first thing they ran.
	//
	// "dev" is written rather than Version, deliberately. Version is what the
	// *generating* binary carries, so a release build regenerating this file
	// would produce a different README from a source build and the --check gate
	// would flip on who ran it. "dev" is what anybody building from a checkout
	// sees, which is who reads a README; a released binary prints its tag there.
	fmt.Fprintf(&b, "```bash\nfeint serve\n#  feint dev listening on %s\n", DefaultAddr)
	for _, provider := range order {
		fmt.Fprintf(&b, "#    %-9s %2d routes\n", provider, routeTotal(routes[provider]))
	}
	b.WriteString("#    machines  none\n```\n")
	return b.String()
}

// percent renders a share without pretending to a precision the numbers do not
// carry, and without dividing by zero on a provider whose scan found nothing.
func percent(part, whole int) string {
	if whole == 0 {
		return "no measured surface"
	}
	return strconv.Itoa(part*100/whole) + "%"
}

// spliceSection replaces what lies between the markers, leaving everything else
// byte for byte. Rewriting the whole file from a template would put the prose at
// the mercy of the generator.
func spliceSection(doc, startMarker, endMarker, section string) (string, error) {
	start := strings.Index(doc, startMarker)
	end := strings.Index(doc, endMarker)
	switch {
	case start < 0 || end < 0:
		return "", fmt.Errorf("no %s / %s markers to write between", startMarker, endMarker)
	case end < start:
		return "", fmt.Errorf("%s comes before %s", endMarker, startMarker)
	}

	var b bytes.Buffer
	b.WriteString(doc[:start+len(startMarker)])
	b.WriteString("\n")
	b.WriteString(section)
	b.WriteString(doc[end:])
	return b.String(), nil
}

// contractFile is the header of an API description artefact. Only the fields the
// table needs: this is a reader of a format, and reading less of it is what keeps
// it working when the writer grows a field.
type contractFile struct {
	Provider     string         `json:"provider"`
	Source       string         `json:"source"`
	APIVersion   string         `json:"apiVersion"`
	ClosedPolicy string         `json:"closedPolicy"`
	Schemas      map[string]any `json:"schemas"`
}

// spliceContracts renders the contract policy table and reports whether the file
// would change. It returns false with no error when the file does not exist,
// because a binary installed from a release has no docs/ beside it.
func spliceContracts(path, dir string) (bool, error) {
	if path == "" {
		return false, nil
	}
	current, err := os.ReadFile(path) //nolint:gosec // an operator-supplied path, read only
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if !strings.Contains(string(current), contractsStartMarker) {
		// A Markdown file that never claimed to carry this table.
		return false, nil
	}
	rendered, err := renderContracts(dir)
	if err != nil {
		return false, err
	}
	updated, err := spliceSection(string(current), contractsStartMarker, contractsEndMarker, rendered)
	if err != nil {
		return false, err
	}
	return updated != string(current), nil
}

func writeSplicedContracts(path, dir string) error {
	current, err := os.ReadFile(path) //nolint:gosec // same path as above
	if err != nil {
		return err
	}
	rendered, err := renderContracts(dir)
	if err != nil {
		return err
	}
	updated, err := spliceSection(string(current), contractsStartMarker, contractsEndMarker, rendered)
	if err != nil {
		return err
	}
	return os.WriteFile(path, []byte(updated), 0o644) //nolint:gosec // documentation is world-readable by design
}

// renderContracts builds the table.
//
// The count is of schemas *extracted*, not of schemas the provider closed. That
// distinction is the whole point: for a provider whose policy is "assumed", a
// closed-schema count would measure this project's own --assume-closed flag and
// read like evidence about theirs. The policy column carries the fact that
// matters, and the count carries only what it honestly is.
func renderContracts(dir string) (string, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return "", err
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString(docsGenerated)
	b.WriteString("\n\n| Provider | API description | Schemas | Unknown fields |\n")
	b.WriteString("|---|---|--:|---|\n")

	for _, path := range paths {
		raw, readErr := os.ReadFile(path) //nolint:gosec // the path comes from our own glob
		if readErr != nil {
			return "", readErr
		}
		var doc contractFile
		if err := json.Unmarshal(raw, &doc); err != nil {
			return "", fmt.Errorf("%s: %w", path, err)
		}
		if doc.Provider == "" {
			continue
		}
		policy := doc.ClosedPolicy
		switch policy {
		case "declared":
			policy = "**declared** by the provider"
		case "assumed":
			policy = "*assumed* by this emulator"
		case "":
			policy = "not recorded"
		}
		fmt.Fprintf(&b, "| %s | `%s` | %d | %s |\n",
			strings.ToUpper(doc.Provider[:1])+doc.Provider[1:], doc.APIVersion, len(doc.Schemas), policy)
	}
	return b.String(), nil
}
