package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/stephrobert/feint/internal/contract"
	"github.com/stephrobert/feint/internal/drift"
	"github.com/stephrobert/feint/internal/trace"
	"github.com/stephrobert/feint/internal/transcript"
)

// observedCoverage answers the question `Declined()` cannot: of everything this
// pack refuses, what has a real client actually asked for?
//
// It is the half of #74 that survived its own rescoping. The other half —
// ordering the untriaged queue — had no subject left by the time it was built:
// coverage/*-coverage.json reports 0 untriaged on all three providers, so there
// is no queue to order. The untriaged ranking is still computed and still
// printed, because the queue refills at every SDK bump and a view that only
// works when the number is zero is a view nobody trusts when it is not.
//
// Read-only and offline: it opens files, builds the packs in process, and talks
// to nothing.
func observedCoverage(rep drift.Report, doc *contract.Doc, path, format string, stdout, stderr io.Writer) int {
	if doc == nil {
		fmt.Fprintln(stderr, "feint: --observed needs --contract: naming the operation a recorded call addressed is the")
		fmt.Fprintln(stderr, "feint: provider document's job, and a declined operation has no route to name it by")
		return exitError
	}

	files, err := recordingsUnder(path)
	if err != nil {
		fmt.Fprintf(stderr, "feint: %v\n", err)
		return exitError
	}

	index := operationIndex(rep, doc)
	calls := drift.Calls{Count: map[string]int{}, Clients: map[string]string{}}
	byOperation := map[string][]*trace.Exchange{}
	unattributed := 0
	for _, file := range files {
		exs, err := loadTranscript(file)
		if err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
		for i := range exs {
			x := &exs[i]
			name, ok := attribute(index, doc, x)
			if !ok {
				unattributed++
				continue
			}
			calls.Count[name]++
			byOperation[name] = append(byOperation[name], x)
		}
	}
	for name, exs := range byOperation {
		calls.Clients[name] = transcript.ClientsOf(exs)
	}

	observed := rep.Observe(calls, unattributed)
	switch format {
	case "json":
		if err := writeJSON(stdout, observed); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
	default:
		// text, triage and list all render the observed view: --observed asks a
		// different question from the one --format selects, and mixing the two
		// into one document would risk the committed artefact, which is
		// generated by `feint coverage --format json` with no --observed.
		if err := observed.WriteObserved(stdout); err != nil {
			fmt.Fprintf(stderr, "feint: %v\n", err)
			return exitError
		}
	}
	return exitOK
}

// attribute names the report operation a recorded exchange addressed.
//
// Two steps, and the order is what makes a declined operation nameable at all:
//
//  1. the contract resolves the concrete path to the provider's own operation
//     id, which exists for every operation the document describes, served or
//     not;
//  2. that id is joined back to the report's spelling, which is the SDK's.
func attribute(index map[string]string, doc *contract.Doc, x *trace.Exchange) (string, bool) {
	key, ok := doc.OperationAt(x.Method, x.Path)
	if !ok {
		return "", false
	}
	name, ok := index[key]
	return name, ok
}

// operationIndex maps a contract operation id to the report's spelling of the
// same operation.
//
// Built from the report rather than from the document, and the direction
// matters: the report is the authority on which operations this provider has —
// it is what the baseline and the committed artefact are made of — while the
// contract is consulted only for where each one lives. An id the report has no
// entry for is left out, so a recorded call to an operation outside the scanned
// products counts as unattributed instead of inventing a row nothing can be
// held against.
func operationIndex(rep drift.Report, doc *contract.Doc) map[string]string {
	index := make(map[string]string, len(rep.Entries))
	for _, e := range rep.Entries {
		if _, key, ok := doc.OperationFor(e.Operation); ok {
			index[key] = e.Operation
		}
	}
	return index
}

// recordingsUnder takes a file or a directory of them.
//
// A directory, because a measurement is rarely one run: #74 asks for "one
// recording, or a directory of them". A directory with no .jsonl in it is an
// error rather than an empty ranking — a report drawn from nothing must not
// read as a report drawn from a clean run.
func recordingsUnder(path string) ([]string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, fmt.Errorf("read the recordings at %s: %w", path, err)
	}
	if !info.IsDir() {
		return []string{path}, nil
	}
	entries, err := os.ReadDir(path)
	if err != nil {
		return nil, fmt.Errorf("read the recordings in %s: %w", path, err)
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".jsonl") {
			continue
		}
		files = append(files, filepath.Join(path, e.Name()))
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("no .jsonl recording in %s: a ranking drawn from nothing reads like a clean run", path)
	}
	sort.Strings(files)
	return files, nil
}
