# The provider's own examples/net_vm, adapted to the emulated catalogue.
#
# This is OSC-3's closing condition (#10) and, more to the point, the only thing
# that says whether the routing family holds TOGETHER. Every route below had a
# unit test and passed the contract before this file existed, and neither can see
# what a real client does across resources: an id read back in the wrong shape, a
# dependency the provider walks in an order the pack refuses, an attribute that
# plans a change on the second run.
#
# What is faithful to the upstream example: the thirteen resources and the
# dependency graph between them — Net, Subnet, InternetService and its link,
# RouteTable, its link and a default route through the gateway, SecurityGroup
# and a rule, PublicIp and its link onto the machine, Keypair, Vm.
#
# What is adapted, and why:
#
#   - the image and the type come from the emulated catalogue (catalog.go), not
#     from Outscale's, because the emulator sells three machines and no others;
#   - the keypair is a fixed public key rather than one generated by the `tls`
#     provider, and there is no `local_file`: a conformance run must not need two
#     more providers downloaded, and writing a private key into a temp dir is not
#     something a CI job should do;
#   - no `random_string` suffix, for the same reason. The names are fixed, and
#     the suite destroys what it creates.
#
# The `osc.fcu.eip.auto-attach` tag of the upstream example is deliberately NOT
# reproduced: it asks the platform to attach the address by itself, which is
# behaviour the emulator does not have, and the explicit
# `outscale_public_ip_link` below is what the pack actually serves.

# The tags block is the whole of issue #99, and it is here rather than in a unit
# test because only the provider walks this path: it creates the resource, then
# calls CreateTags with the identifier it just received. The emulator answered
# "the resource igw-… does not exist" about a resource it was serving, because
# the prefix table in tags.go had never grown past the four kinds the pack had
# when it was written. An apply of this file fails without the fix.
resource "outscale_internet_service" "net_vm" {
  tags {
    key   = "Name"
    value = "conformance-igw"
  }
}

resource "outscale_internet_service_link" "net_vm" {
  internet_service_id = outscale_internet_service.net_vm.internet_service_id
  net_id              = outscale_net.conformance.net_id
}

# Tagged for the same reason, and on purpose on a second family: rtb- and sg-
# were reported failing beside igw-, and the defect was a missing row per
# prefix rather than one wrong line.
resource "outscale_route_table" "net_vm" {
  net_id = outscale_net.conformance.net_id

  tags {
    key   = "Name"
    value = "conformance-rtb"
  }
}

resource "outscale_route_table_link" "net_vm" {
  subnet_id      = outscale_subnet.conformance.subnet_id
  route_table_id = outscale_route_table.net_vm.route_table_id
}

# The route depends on the gateway being linked to the Net, and the pack refuses
# it otherwise — deliberately, because the real API does. Terraform does not
# infer that ordering from the arguments, so it is stated.
resource "outscale_route" "net_vm" {
  destination_ip_range = "0.0.0.0/0"
  gateway_id           = outscale_internet_service.net_vm.internet_service_id
  route_table_id       = outscale_route_table.net_vm.route_table_id

  depends_on = [outscale_internet_service_link.net_vm]
}

resource "outscale_security_group" "net_vm" {
  description         = "feint conformance net_vm"
  net_id              = outscale_net.conformance.net_id
  security_group_name = "feint-conformance-sg"
}

resource "outscale_security_group_rule" "net_vm" {
  flow              = "Inbound"
  security_group_id = outscale_security_group.net_vm.security_group_id

  rules {
    from_port_range = "22"
    to_port_range   = "22"
    ip_protocol     = "tcp"
    ip_ranges       = ["198.51.100.0/24"]
  }
}

resource "outscale_public_ip" "net_vm" {}

# Control plane only: the record moves, no packet does. docs/limits.md says so.
# It is here because the upstream example has it, and declining it failed the
# apply on the eleventh resource of thirteen.
resource "outscale_public_ip_link" "net_vm" {
  vm_id     = outscale_vm.conformance.vm_id
  public_ip = outscale_public_ip.net_vm.public_ip
}

# Beyond the upstream example, and for a stated reason: OSC-3 promises "Nic and
# its links" and "NatService", the pack serves all of them, and no client drove
# a single one — six routes whose behaviour was held by unit tests alone. The
# batch's own closing condition says a unit test closes nothing.
#
# A NIC is also the one resource here that carries an address of its own, so a
# client attaching one is the only thing that exercises the second-interface
# path of the addressing plane.
resource "outscale_nic" "net_vm" {
  subnet_id          = outscale_subnet.conformance.subnet_id
  security_group_ids = [outscale_security_group.net_vm.security_group_id]

  # From a variable so the second apply can change it in place: description is
  # one of the two attributes ResourceOutscaleNicUpdate sends UpdateNic for
  # (the other is security_group_ids; subnet_id forces a replacement). Set
  # explicitly from the first apply, so the change the suite makes later is a
  # change to a value this fixture owns rather than to a computed default.
  description = var.nic_description
}

resource "outscale_nic_link" "net_vm" {
  device_number = "1"
  vm_id         = outscale_vm.conformance.vm_id
  nic_id        = outscale_nic.net_vm.nic_id
}

# Its own address, not the machine's: a NAT service and a linked public IP
# cannot share one, and the pack refuses it — which is the behaviour a second
# address proves rather than assumes.
resource "outscale_public_ip" "nat" {}

resource "outscale_nat_service" "net_vm" {
  subnet_id    = outscale_subnet.conformance.subnet_id
  public_ip_id = outscale_public_ip.nat.public_ip_id

  depends_on = [outscale_route_table_link.net_vm]
}

# The one resource that sends UpdateRouteTableLink. `outscale_route_table_link`
# never does: its Update is empty and both attributes carry RequiresReplace
# (resource_route_table_link.go, v1.8.0), so re-pointing one is an unlink and a
# link. This resource re-points the Net's *main* link instead — Create moves it
# onto this table with UpdateRouteTableLink, and Delete moves it back onto the
# default table with the same call, so a destroy drives the operation a second
# time. The destroy also proves the restore worked: the pack refuses to delete
# a table that still holds the main link.
resource "outscale_main_route_table_link" "net_vm" {
  net_id         = outscale_net.conformance.net_id
  route_table_id = outscale_route_table.net_vm.route_table_id
}

output "internet_service_id" {
  value = outscale_internet_service.net_vm.internet_service_id
}

output "nic_id" {
  value = outscale_nic.net_vm.nic_id
}

output "nat_service_id" {
  value = outscale_nat_service.net_vm.nat_service_id
}

output "route_table_id" {
  value = outscale_route_table.net_vm.route_table_id
}

output "security_group_id" {
  value = outscale_security_group.net_vm.security_group_id
}

output "public_ip" {
  value = outscale_public_ip.net_vm.public_ip
}
