# The provider's own examples/net_vm, adapted to the emulated catalogue.
#
# This is OSC-3's closing condition (#10) and, more to the point, the only thing
# that says whether the routing family holds TOGETHER. Every route below had a
# unit test and passed the contract before this file existed, and neither can see
# what a real client does across resources: an id read back in the wrong shape, a
# dependency the provider walks in an order the pack refuses, an attribute that
# plans a change on the second run.
#
# What is faithful to the upstream example: the thirteen resources and the
# dependency graph between them — Net, Subnet, InternetService and its link,
# RouteTable, its link and a default route through the gateway, SecurityGroup
# and a rule, PublicIp and its link onto the machine, Keypair, Vm.
#
# What is adapted, and why:
#
#   - the image and the type come from the emulated catalogue (catalog.go), not
#     from Outscale's, because the emulator sells three machines and no others;
#   - the keypair is a fixed public key rather than one generated by the `tls`
#     provider, and there is no `local_file`: a conformance run must not need two
#     more providers downloaded, and writing a private key into a temp dir is not
#     something a CI job should do;
#   - no `random_string` suffix, for the same reason. The names are fixed, and
#     the suite destroys what it creates.
#
# The `osc.fcu.eip.auto-attach` tag of the upstream example is deliberately NOT
# reproduced: it asks the platform to attach the address by itself, which is
# behaviour the emulator does not have, and the explicit
# `outscale_public_ip_link` below is what the pack actually serves.

resource "outscale_internet_service" "net_vm" {}

resource "outscale_internet_service_link" "net_vm" {
  internet_service_id = outscale_internet_service.net_vm.internet_service_id
  net_id              = outscale_net.conformance.net_id
}

resource "outscale_route_table" "net_vm" {
  net_id = outscale_net.conformance.net_id
}

resource "outscale_route_table_link" "net_vm" {
  subnet_id      = outscale_subnet.conformance.subnet_id
  route_table_id = outscale_route_table.net_vm.route_table_id
}

# The route depends on the gateway being linked to the Net, and the pack refuses
# it otherwise — deliberately, because the real API does. Terraform does not
# infer that ordering from the arguments, so it is stated.
resource "outscale_route" "net_vm" {
  destination_ip_range = "0.0.0.0/0"
  gateway_id           = outscale_internet_service.net_vm.internet_service_id
  route_table_id       = outscale_route_table.net_vm.route_table_id

  depends_on = [outscale_internet_service_link.net_vm]
}

resource "outscale_security_group" "net_vm" {
  description         = "feint conformance net_vm"
  net_id              = outscale_net.conformance.net_id
  security_group_name = "feint-conformance-sg"
}

resource "outscale_security_group_rule" "net_vm" {
  flow              = "Inbound"
  security_group_id = outscale_security_group.net_vm.security_group_id

  rules {
    from_port_range = "22"
    to_port_range   = "22"
    ip_protocol     = "tcp"
    ip_ranges       = ["198.51.100.0/24"]
  }
}

resource "outscale_public_ip" "net_vm" {}

# Control plane only: the record moves, no packet does. docs/limits.md says so.
# It is here because the upstream example has it, and declining it failed the
# apply on the eleventh resource of thirteen.
resource "outscale_public_ip_link" "net_vm" {
  vm_id     = outscale_vm.conformance.vm_id
  public_ip = outscale_public_ip.net_vm.public_ip
}

output "internet_service_id" {
  value = outscale_internet_service.net_vm.internet_service_id
}

output "route_table_id" {
  value = outscale_route_table.net_vm.route_table_id
}

output "security_group_id" {
  value = outscale_security_group.net_vm.security_group_id
}

output "public_ip" {
  value = outscale_public_ip.net_vm.public_ip
}
